# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97a759d1d60608a80d8096a2a7ad4eaf8ca6589e73353866e0274bb7806b130c8a27b890830c472100db9af59b51e4c8aadbf2808b876ccda4f1672ac4ae01fe

test:
  secret_key_base: 63b9b8f01ec1b50269e4401f34641e53b416e12ee612adb372ca453c55efb297dc5389eb2aa0de2002a22129195f8c9ab72d242fc9f19585ae4b2a24cd699cdf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
